package com.dig_i.front.entity;

public enum ResourceCategory {
	UNDEFINED, POLITICS, ECONOMY, SOCIETY, CULTURE, WORLD, COMPANY, ENTERTAINMENT, MOVIE, ELECTRONICS, IT, HOBBY, SPORTS, MUSIC, TECHNOLOGY, TRADITION, DESIGN, MEDIA, INTERNET, RESION, RELIGION, INTERNATIONAL, SCIENCE, BUSINESS, LIFE, TRAVEL, BEAUTY, HEALTH, FASHION, MANNERS, WORK, ADVERTISEMENT, COOKING, FOOD, PRIZE, EXCHANGE, PLAY, LEISURE, DRAMA, PERFORMANCE, GAME, TREND, TOPIC, ITEM, BLOG, BOOK, GOURMET, MACHINE, IMAGE, PICTURE, SITE, SERVICE, ART, SYNTHESIS, OTHERS;
}
